services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kelvin_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    env_file:
      - .env
    networks:
      - kelvin_network

  db:
    image: mysql:8.0
    container_name: kelvin_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./dbdata:/var/lib/mysql
    env_file:
      - .env
    networks:
      - kelvin_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: kelvin_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: ${DB_PASSWORD}
      PMA_ABSOLUTE_URI: https://kevinthompsonphd.com/dbase/
    depends_on:
      - db
    networks:
      - kelvin_network

  nginx:
    image: nginx:alpine
    container_name: kelvin_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - app
      - phpmyadmin
    networks:
      - kelvin_network

networks:
  kelvin_network:
    driver: bridge